# ============================================================
# Project variables
# ============================================================

variable "aws_access_key" {
  type        = string
  description = "AWS Access Key ID"
  sensitive   = true
}

variable "aws_secret_key" {
  type        = string
  description = "AWS Secret Access Key"
  sensitive   = true
}

variable "aws_region" {
  type        = string
  description = "AWS region for both instances"
  default     = "eu-north-1"
}

variable "instance_type" {
  type        = string
  description = "EC2 instance type (free tier)"
  default     = "t3.micro"
}

variable "admin_cidr" {
  type        = string
  description = "CIDR allowed to reach the instances over SSH (22/tcp). Lock it down to your public IP for anything but a short-lived lab."
  default     = "0.0.0.0/0"
}

variable "key_name" {
  type        = string
  description = "Name of the AWS key pair generated by this configuration"
  default     = "cmd521-key"
}
